apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackjack-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackjack
  template:
    metadata:
      labels:
        app: blackjack
    spec:
      containers:
      - name: blackjack-container
        image: blackjack-terminal:latest
        ports:
        - containerPort: 7681